services:
 paddy-classification:
   build:
     context: .
     dockerfile: env/Dockerfile
   deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   ipc: host
   ports:
     - 8888:8888
   volumes:
     - ./config:/workspace/config
     - ../data:/workspace/data
     - ./inputs:/workspace/inputs
     - ./model:/workspace/model
     - ./notebooks:/workspace/notebooks
     - ./outputs:/workspace/outputs
     - ./src:/workspace/src
   working_dir: /workspace